OpenAI/OpenAI/Controllers/GenAIToolsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OpenAI.Models;

namespace OpenAI.Controllers
{
    public class GenAIToolsController : Controller
    {
        private readonly GenAIToolsDbContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;

        public GenAIToolsController(GenAIToolsDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            this._hostEnvironment = hostEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            return _context.DbSet != null ?
                        View(await _context.DbSet.ToListAsync()) :
                        Problem("Entity set 'GenAIToolsDbContext.DbSet'  is null.");
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.DbSet == null)
            {
                return NotFound();
            }

            var genAIToolsModel = await _context.DbSet
                .FirstOrDefaultAsync(m => m.Id == id);
            if (genAIToolsModel == null)
            {
                return NotFound();
            }

            return View(genAIToolsModel);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,GenAIName,Summary,ImageFilename,ImageFile,AnchorLink,Like")] GenAIToolsModel genAIToolsModel)
        {
            if (ModelState.IsValid)
            {
                //Save Image to wwwRoot/image
                string wwwRootPath = _hostEnvironment.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(genAIToolsModel.ImageFile.FileName);
                string extension = Path.GetExtension(genAIToolsModel.ImageFile.FileName);
                genAIToolsModel.ImageFilename = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                string path = Path.Combine(wwwRootPath + "/images/", genAIToolsModel.ImageFilename);
                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    await genAIToolsModel.ImageFile.CopyToAsync(fileStream);
                }

                _context.Add(genAIToolsModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(genAIToolsModel);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.DbSet == null)
            {
                return NotFound();
            }

            var genAIToolsModel = await _context.DbSet.FindAsync(id);
            if (genAIToolsModel == null)
            {
                return NotFound();
            }
            return View(genAIToolsModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,GenAIName,Summary,ImageFilename,AnchorLink,Like")] GenAIToolsModel genAIToolsModel)
        {
            if (id != genAIToolsModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(genAIToolsModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GenAIToolsModelExists(genAIToolsModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(genAIToolsModel);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.DbSet == null)
            {
                return NotFound();
            }

            var genAIToolsModel = await _context.DbSet
                .FirstOrDefaultAsync(m => m.Id == id);
            if (genAIToolsModel == null)
            {
                return NotFound();
            }

            return View(genAIToolsModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.DbSet == null)
            {
                return Problem("Entity set 'GenAIToolsDbContext.DbSet'  is null.");
            }

            var genAIToolsModel = await _context.DbSet.FindAsync(id);

            if (genAIToolsModel != null)
            {
                //delete image from wwwRoot/image
                var imagePath = Path.Combine(_hostEnvironment.WebRootPath, "image", genAIToolsModel.ImageFilename);
                if (System.IO.File.Exists(imagePath))
                {
                    System.IO.File.Delete(imagePath);
                }
                _context.DbSet.Remove(genAIToolsModel);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GenAIToolsModelExists(int id)
        {
            return (_context.DbSet?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

OpenAI/OpenAI/Controllers/UserRegistrationController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OpenAI.Models;

namespace OpenAI.Controllers
{
    public class UserRegistrationController : Controller
    {
        private readonly GenAIToolsDbContext _context;
        public UserRegistrationController(GenAIToolsDbContext context)
        {
            _context = context;
        }

        // GET: UserRegistrationController
        public async Task<ActionResult> Index()
        {
            return _context.UserRegitrationSet != null ?
                        View(await _context.UserRegitrationSet.ToListAsync()) :
                        Problem("Entity set 'GenAIToolsDbContext.UserRegitrationSet'  is null.");
        }

        // GET: UserRegistrationController/Create
        public ActionResult LogIn()
        {
            return View();
        }

        // POST: UserRegistrationController/Create
        [HttpGet]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LogIn([Bind("Username,Password")] UserRegistrationModel userRegitrationModel)
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction("Index", "HomeController");
            }
            return View(userRegitrationModel);
        }

        // GET: UserRegistrationController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserRegistrationController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Username,Password,IsAdmin")] UserRegistrationModel userRegitrationModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(userRegitrationModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(userRegitrationModel);
        }
    }
}

OpenAI/OpenAI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OpenAI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OpenAI.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="fixedHeader">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-black">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">OpenAI</a>
                <button class="navbar-light navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="GenAI">GenAI</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Jobs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="GenAITools" asp-action="Index">GenAISites</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav flex-end">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="UserRegistration" asp-action="Create">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="UserRegistration" asp-action="LogIn">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>

    <div class="container">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <div class="divFooter">
        <div class="container">
            <div class="row text-light p-5">
                <div class="col-sm-3">
                    <a asp-area="" class="text-light" asp-controller="Home" asp-action="Index">Home</a><br />
                    <a asp-area="" class="text-light" asp-controller="GenAITools" asp-action="Index">GenAISites</a><br />
                </div>
                <div class="col-sm-3">
                    <a asp-area="" class="text-light" asp-controller="Home" asp-action="Index">Jobs</a><br />
                    <a asp-area="" class="text-light" asp-controller="Home" asp-action="Contact">Contact</a><br />
                </div>
                <div class="col-sm-3">
                    <a asp-area="" class="text-light" asp-controller="Home" asp-action="Contact">About Us</a><br />
                    <a asp-area="" class="text-light" asp-controller="Home" asp-action="Privacy">Copyright Info</a><br />
                </div>
                <div class="col-sm-3">
                    <a asp-area="" class="text-light" asp-controller="Home" asp-action="Contact">Follow Us</a><br />
                    <div class="text-light">
                        <button class="btn btn-sm btn-light"><i class="fa-brands fa-facebook"></i></button>
                        <button class="btn btn-sm btn-light"><i class="fa-brands fa-youtube"></i></button>
                        <button class="btn btn-sm btn-light"><i class="fa-brands fa-linkedin"></i></button>
                        <button class="btn btn-sm btn-light"><i class="fa-brands fa-twitter"></i></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>